const express = require("express");
const router = express.Router();

const Scenario = require("../model/Scenerio"); // make sure spelling matches file
const Agent = require("../model/Agent");


// ================= CREATE SCENARIO =================
router.post("/agents/:agentId/scenarios", async (req, res) => {
  try {
    const { name, description, userMessage, expectedTools, complexity, targetCategory } = req.body;
    const { agentId } = req.params;

    // 🔹 Check if agent exists
    const agentExists = await Agent.findById(agentId);
    if (!agentExists) {
      return res.status(404).json({ error: "Agent not found" });
    }

    // 🔹 Validation
    if (!name || name.length < 3 || name.length > 100) {
      return res.status(400).json({ error: "Name must be 3–100 characters" });
    }

    if (!userMessage || userMessage.length < 10 || userMessage.length > 500) {
      return res.status(400).json({ error: "User message must be 10–500 characters" });
    }

    if (expectedTools && !Array.isArray(expectedTools)) {
      return res.status(400).json({ error: "Expected tools must be an array" });
    }

    const scenario = await Scenario.create({
      agentId,
      name,
      description,
      userMessage,
      expectedTools,
      complexity,
      targetCategory,
      isAutoGenerated: false
    });

    res.status(201).json(scenario);

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Server error" });
  }
});


// ================= LIST SCENARIOS (PAGINATED) =================
router.get("/agents/:agentId/scenarios", async (req, res) => {
  try {
    const { agentId } = req.params;
    const page = parseInt(req.query.page) || 1;
    const limit = 20;
    const skip = (page - 1) * limit;

    const scenarios = await Scenario.find({ agentId })
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit);

    res.json(scenarios);

  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});


// ================= GET SINGLE SCENARIO =================
router.get("/scenarios/:id", async (req, res) => {
  try {
    const scenario = await Scenario.findById(req.params.id);

    if (!scenario) {
      return res.status(404).json({ error: "Scenario not found" });
    }

    res.json(scenario);

  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});


// ================= DELETE SCENARIO =================
router.delete("/scenarios/:id", async (req, res) => {
  try {
    const deletedScenario = await Scenario.findByIdAndDelete(req.params.id);

    if (!deletedScenario) {
      return res.status(404).json({ error: "Scenario not found" });
    }

    res.json({ message: "Scenario deleted successfully" });

  } catch (err) {
    res.status(500).json({ error: "Server error" });
  }
});

module.exports = router;