const mongoose = require('mongoose')

const expectedToolSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true
  },
  parameters: {
    type: Object,
    default: {}
  }
}, { _id: false })

const scenarioSchema = new mongoose.Schema({

  agentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Agent",
    required: true
  },

  name: {
    type: String,
    required: true,
    minlength: 3,
    maxlength: 100
  },

  description: {
    type: String
  },

  userMessage: {
    type: String,
    required: true,
    minlength: 10,
    maxlength: 500
  },

  expectedTools: {   // ⭐ THIS WAS MISSING
    type: [expectedToolSchema],
    default: []
  },

  complexity: {
    type: String,
    enum: ["simple", "moderate", "high"],
    default: "simple"
  },

  targetCategory: {
    type: String,
    enum: ["edge_case", "happy_path", "adversarial", "other"],
    default: "happy_path"
  },

  isAutoGenerated: {
    type: Boolean,
    default: false
  }

}, {
  timestamps: true
})

module.exports = mongoose.model("Scenario", scenarioSchema)